apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-app-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-app-client
  template:
    metadata:
      labels:
        app: movie-app-client
    spec:
      containers:
        - name: movie-app-client
          image: amitfegade121/movie-app-client
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: movie-app-client
spec:
  selector:
    app: movie-app-client
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
