apiVersion: v1
kind: ConfigMap
metadata:
  name: movie-info-service-cm
data:
  RDS_HOSTNAME: mysql-svc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-info-service
  labels:
    app: movie-info-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-info-service
  template:
    metadata:
      labels:
        app: movie-info-service
    spec:
      containers:
        - name: movie-info-service
          image: amitfegade121/movie-info-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: RDS_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: movie-info-service-cm
                  key: RDS_HOSTNAME
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USERNAME
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: movie-info-service
spec:
  selector:
    app: movie-info-service
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
