apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-catalog-service
  labels:
    app: movie-catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-catalog-service
  template:
    metadata:
      labels:
        app: movie-catalog-service
    spec:
      containers:
        - name: movie-catalog-service
          image: amitfegade121/movie-catalog-service:latest
          ports:
            - containerPort: 8083

---
apiVersion: v1
kind: Service
metadata:
  name: movie-catalog-service
spec:
  selector:
    app: movie-catalog-service
  type: NodePort
  ports:
    - port: 80
      targetPort: 8083
      nodePort: 31000
