apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqldb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 600Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              value: "movieapp"
          volumeMounts:
            - name: mysql-volume
              mountPath: /var/lib/mysql
          volumes:
            - name: mysql-volume
              persistentVolumeClaim:
                claimName: mysqldb-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  selector:
    app: mysql
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3306
